### PR TITLE
oasp/oasp4js#42: more restrictive dependency declarations …

### LINKED ISSUE #42: gulp build fails
C:\tmp\oasp4js>gulp
[11:52:14] Using gulpfile C:\tmp\oasp4js\gulpfile.js
[11:52:14] Starting 'clean'...
[11:52:14] Finished 'clean' after 6.18 ms
[11:52:14] Starting 'default'...
[11:52:14] Starting 'build:dist'...
[11:52:14] Starting 'wiredep'...
[11:52:14] Starting 'sync group1:0'...
[11:52:14] Starting 'ngTemplatesTasksGeneration'...
[11:52:14] Finished 'ngTemplatesTasksGeneration' after 2.14 ms
[11:52:14] Finished 'sync group1:0' after 3.75 ms
[11:52:14] Starting 'sync group1:1'...
[11:52:14] Starting 'ngTemplates[main.templates.js]'...
[11:52:14] Starting 'ngTemplates[oasp-mock.templates.js]'...
[11:52:14] Starting 'ngTemplates[oasp.templates.js]'...
[11:52:14] Starting 'ngTemplates[oasp-security.templates.js]'...
[11:52:14] Starting 'ngTemplates[oasp-ui.templates.js]'...
[11:52:14] Starting 'ngTemplates[oasp-i18n.templates.js]'...
[11:52:14] Starting 'ngTemplates[offer-mgmt.templates.js]'...
[11:52:14] Starting 'ngTemplates[sales-mgmt.templates.js]'...
[11:52:14] Starting 'ngTemplates[table-mgmt.templates.js]'...
[11:52:14] Starting 'sprite'...
[11:52:14] Starting 'less'...
[11:52:14] Starting 'html'...
[11:52:14] Starting 'img'...
[11:52:15] Starting 'i18n'...
[11:52:15] Starting 'fonts'...
[11:52:15] Finished 'build:dist' after 1.14 s
[11:52:15] Finished 'default' after 1.14 s
C:\tmp\oasp4js\node_modules\gulp-ng-templates\node_modules\gulp-header\index.js:
58
    var file = _file.clone({ contents: false });
                    ^
TypeError: Cannot read property 'clone' of undefined
    at DestroyableTransform.EndStream [as _flush] (C:\tmp\oasp4js\node_modules\g
ulp-ng-templates\node_modules\gulp-header\index.js:58:21)
    at DestroyableTransform.<anonymous> (C:\tmp\oasp4js\node_modules\through2\no
de_modules\readable-stream\lib\_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:104:17)
    at prefinish (C:\tmp\oasp4js\node_modules\through2\node_modules\readable-str
eam\lib\_stream_writable.js:492:12)
    at finishMaybe (C:\tmp\oasp4js\node_modules\through2\node_modules\readable-s
tream\lib\_stream_writable.js:500:7)
    at endWritable (C:\tmp\oasp4js\node_modules\through2\node_modules\readable-s
tream\lib\_stream_writable.js:512:3)
    at DestroyableTransform.Writable.end (C:\tmp\oasp4js\node_modules\through2\n
ode_modules\readable-stream\lib\_stream_writable.js:477:5)
    at DestroyableTransform.onend (C:\tmp\oasp4js\node_modules\gulp-concat\node_
modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)

C:\tmp\oasp4js>

seems to stem from a dependency update, related issue/fix I've found:
https://github.com/google/material-design-lite/commit/618c51fbfa1989d4e99114fe4c78d9d20b707cef

### PR DESCRIPTION
**Pull request by may-bee**
…to prevent from future dependency evolution problems.
Fixes #42

### CODE REVIEW

**Comment by may-bee** [comment]
If someone can merge this soon, I can synchronize the latest changes with the training repository for oasp4js soon. Hope for someones help :)

**Comment by may-bee** [comment]
Can someone merge this?

**Comment by dumbNickname** [comment]
Hey.

Imho looks fine. No doubts were raised and this pull request hangs for a while already, so I hope that nobody will get unhappy with me merging it : )

**Comment by dumbNickname** [comment]
I resolved the conflicts, however please check if I did not miss anything.

Cheers,
Bartek

**Comment by may-bee** [comment]
Looks promising and as the build remains stable, I am fine with it. 
Thanks.

**Pull request merged**
